# Generated by Django 5.0.4 on 2024-04-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MACHINEID', models.CharField(max_length=255)),
                ('DATE', models.DateTimeField()),
                ('OPERATORID', models.CharField(max_length=255)),
                ('STARTTIME', models.TimeField()),
                ('ENDTIME', models.TimeField()),
                ('MODE', models.CharField(max_length=255)),
                ('RAWSTITCHCOUNT', models.IntegerField()),
                ('INLSTITCHCOUNT', models.IntegerField()),
                ('INLRUNTIME', models.IntegerField()),
                ('INLSTOPTIME', models.IntegerField()),
                ('PICKDISPOSETIME', models.IntegerField()),
                ('MANUALSTITCHESPERPIECE', models.IntegerField()),
                ('MANUALPIECECOUNT', models.IntegerField()),
                ('AUTOSTITCHESPERPIECE', models.IntegerField()),
                ('AUTOPIECECOUNT', models.IntegerField()),
                ('CUTTERCOUNT', models.IntegerField()),
                ('DUMMYDATA1', models.CharField(max_length=255)),
                ('DUMMYDATA2', models.CharField(max_length=255)),
            ],
        ),
    ]
